
server:
  port: 8761
#  port: 8762

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/

spring:
  application:
    name: eureka-server-multi-auto
